---
name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  vader:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vim-tag: ["v9.1.0"]
    steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Clone Vim
          run: |
            git clone https://github.com/vim/vim.git
        - name: Checkout and Build Vim ${{ matrix.vim-tag }}
          run: |
            cd vim/
            git checkout ${{ matrix.vim-tag }}
            cd src/
            ./configure \
              --disable-gpm \
              --disable-nls \
              --disable-sysmouse \
              --enable-gui=no \
              --enable-multibyte \
              --enable-python3interp \
              --with-features=huge \
              --with-tlib=ncurses \
              --without-x
            make -j$(nproc)
            sudo make install
        - name: Verify version
          run: |
            vim --version
        - name: Run Vader Tests
          run: |
            git clone https://github.com/junegunn/vader.vim.git
            vim -Nu <(cat << VIMRC
            set rtp+=vader.vim
            set rtp+=.
            VIMRC) -c 'Vader! test/test_*.vader' > /dev/null
